name: Update Billboard Hot 100 JSON

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 * * 1"   # Pazartesi 06:00 UTC

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
      - name: Run scraper
        working-directory: Tools
        run: |
          python -u update_billboard.py
      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore: auto-update Billboard JSON ($(date -u +'%Y-%m-%d'))"
            git push
          else
            echo "No changes to commit."
          fi
